//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsBarCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vijesti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vijesti()
        {
            this.Komentari = new HashSet<Komentari>();
            this.Svidanja = new HashSet<Svidanja>();
            this.Tagovi = new HashSet<Tagovi>();
        }
    
        public int Id { get; set; }
        public Nullable<int> AutorId { get; set; }
        public string Autor { get; set; }
        public string Naslov { get; set; }
        public string Slika { get; set; }
        public string Tekst { get; set; }
        public Nullable<int> Kategorija { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Edited { get; set; }
    
        public virtual Kategorije Kategorije { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komentari> Komentari { get; set; }
        public virtual Korisnici Korisnici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Svidanja> Svidanja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tagovi> Tagovi { get; set; }
    }
}
